<?php
/**
 * Template for the header of all admin pages for tinypass plugin
 * Rendered by @see WPTinypassAdmin
 * @var WPTinypassAdmin $this
 */
?>
<div class="wrap">
	<div class="tinypass-header-logo"></div>
	<?php // This will display any error generated by tinypass plugin ?>
	<?php settings_errors( $this::SETTINGS_ERROR_SLUG ) ?>
	<?php if ( ( $this::$business_model == TinypassConfig::BUSINESS_MODEL_SUBSCRIPTION ) && ( ! isset( $_GET['reset'] ) ) ): ?>
		<h2 class="nav-tab-wrapper">
			<a href="<?php echo esc_url( admin_url( 'admin.php?page=' . $this::SETTINGS_PAGE_SLUG ) ) ?>" class="nav-tab <?php if ( isset( $_GET['page'] ) && ( $_GET['page'] == $this::SETTINGS_PAGE_SLUG ) ): ?> nav-tab-active tinypass-nav-tab-active <?php endif ?>"><?php esc_html_e( 'General settings', 'tinypass' ) ?></a>
			<a href="<?php echo esc_url( admin_url( 'admin.php?page=' . $this::SETTINGS_RESOURCES_PAGE_SLUG ) ) ?>" class="nav-tab <?php if ( isset( $_GET['page'] ) && ( $_GET['page'] == $this::SETTINGS_RESOURCES_PAGE_SLUG ) ): ?> nav-tab-active tinypass-nav-tab-active <?php endif ?>"><?php esc_html_e( 'Resources settings', 'tinypass' ) ?></a>
		</h2>
	<?php endif ?>