# Tell Travis to use new container-based infrastructure
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Specify when Travis should build.
branches:
  only:
    - master

# Git clone depth.
git:
  depth: 1

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.0
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.1
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.2
      env: WP_VERSION=latest PHP_LINT=1 WP_PHPCS=1
    - php: 7.2
      env: WP_VERSION=nightly
  fast_finish: true

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"

  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Couple the PHPUnit version to the PHP version.
  - |
    case "$TRAVIS_PHP_VERSION" in
      7.*)
        echo "Using PHPUnit 6.1"
        composer global require "phpunit/phpunit=6.1.*"
        ;;
      *)
        echo "Using PHPUnit 4.8"
        composer global require "phpunit/phpunit=4.8.*"
        ;;
    esac

  # Set up WordPress installation.
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

  # Install Composer dependencies.
  - composer install
  - export PATH=$PATH:`pwd`/vendor/bin/
  - phpenv rehash

  # For debugging.
  - which phpunit
  - phpunit --version
  - which phpcs
  - phpcs --version
  - pwd
  - echo $PATH

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search for PHP syntax errors.
    #
    # Only need to run this once per PHP version.
    - if [[ "$PHP_LINT" == "1" ]]; then find . -type "f" -iname "*.php" -not -path "./vendor/*" | xargs -L "1" php -l; fi

    # WordPress Coding Standards.
    #
    # These are the same across PHP and WordPress, so we need to run them only once.
    #
    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    # @link http://pear.php.net/package/PHP_CodeSniffer/
    - if [[ "$WP_PHPCS" == "1" ]]; then phpcs -v; fi

    # Test the plugin's unit tests
    - phpunit
    - phpunit -c multisite.xml

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
    email: false
